# Single candlestick patterns
HANGING_MAN_BODY = 15.0
HANGING_MAN_HEIGHT = 75.0

SHOOTING_STAR_BODY = 15.0
SHOOTING_STAR_HEIGHT = 25.0 

SPINNING_TOP_BODY = 15.0
SPINNING_TOP_MIN = 40.0
SPINNING_TOP_MAX = 60.0

MARUBOZU_BODY = 98.5

# Dual candlestick patterns
ENGULFING_FACTOR = 1.1 # 10%

TWEEZER_BODY = 15.0
TWEEZER_HL = 0.01
TWEEZER_TOP_BODY = 40.0
TWEEZER_BOTTOM_BODY = 60.0

# Triple candlestick pattern
MORNING_STAR_PREV_BODY = 10.0
MORNING_STAR_PREV_2_BODY = 90.0